/**
 * `bun run site:generate`: translates the site's upstream sources
 * (`upstream/site/`) into `site/generated/` (docs/adr/0034):
 *
 * - `examples/<name>.tsx`: the examples of the docs pages, with hand-written
 *   overrides (`site/examples/overrides/`) for functions that need React.
 * - `home/<card>.tsx`: the cards of the home page.
 * - `docs/<component>.mdx`: the component pages.
 * - `icons.tsx`: the icons the examples import from `@/components/icons`.
 * - `manifest.json`: which page each example belongs to.
 */
import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs"
import path from "node:path"
import { OVERRIDES, SKIPPED } from "../../../site/examples/overrides"
import { REGISTRY_OVERRIDES } from "../../../site/examples/registry-overrides"
import { formatWithBiome } from "../emit/format"
import { ROOT } from "../paths"
import { previewNames, SiteSourcesStore } from "../upstream/site-sources"
import { type DocsContext, transformDocs } from "./docs"
import { buildIconsModule, type IconUse } from "./icons-module"
import {
  applyOverride,
  dropFunctions,
  type FunctionIssue,
  tidyImports,
  translateExample,
} from "./translate"

export const SITE_DIR = path.join(ROOT, "site")
export const GENERATED_DIR = path.join(SITE_DIR, "generated")
const OVERRIDES_DIR = path.join(SITE_DIR, "examples", "overrides")

export interface ExampleEntry {
  /** The component page that previews it. */
  component: string
  /** Why the site has no version of it, when it has none. */
  skipped?: string
}

/** A registry example the create page previews. */
export interface CreateItem {
  name: string
  title: string
  /** Sections left out because they need React and have no override. */
  dropped: string[]
}

export interface SiteManifest {
  commit: string
  examples: Record<string, ExampleEntry>
  create: CreateItem[]
}

export interface MissingOverride extends FunctionIssue {
  example: string
}

export interface SiteOutput {
  /** Path relative to `site/generated/` → content. */
  files: Map<string, string>
  missing: MissingOverride[]
  /** Overrides whose upstream function changed (sha256 mismatch) or vanished. */
  stale: string[]
  /** What was left out without failing (create page items). */
  warnings: string[]
}

const LICENSE =
  "// Derived from shadcn/ui. Copyright (c) 2023 shadcn. MIT License."

function header(source: string, commit: string, notes: string[] = []): string {
  return [
    `// Generated by \`bun run site:generate\` from shadcn/ui ${source} (shadcn-ui/ui@${commit.slice(0, 12)}); do not edit.`,
    ...notes.map((note) => `// ${note}`),
    LICENSE,
  ].join("\n")
}

function format(text: string, file: string): string {
  return formatWithBiome(text, path.join("site/generated", file))
}

interface Translation {
  text: string
  icons: IconUse[]
}

function translate(
  name: string,
  source: string,
  output: SiteOutput
): Translation | null {
  const result = translateExample(name, source)
  const override = OVERRIDES[name]
  let text = result.text
  if (override) {
    for (const [fn, sha256] of Object.entries(override.functions)) {
      const upstream = result.hashes.get(fn)
      if (!upstream) {
        output.stale.push(`${name}#${fn}: the upstream function is gone`)
      } else if (upstream !== sha256) {
        output.stale.push(
          `${name}#${fn}: upstream changed (now sha256 ${upstream}); review the override`
        )
      }
    }
    const file = path.join(OVERRIDES_DIR, `${name}.tsx`)
    if (!existsSync(file)) throw new Error(`missing override file ${file}`)
    text = applyOverride(
      text,
      readFileSync(file, "utf8"),
      Object.keys(override.functions)
    )
  }
  const uncovered = result.issues.filter(
    (issue) => !override?.functions[issue.name]
  )
  if (uncovered.length > 0) {
    output.missing.push(
      ...uncovered.map((issue) => ({ ...issue, example: name }))
    )
    return null
  }
  return {
    text: tidyImports(text),
    icons: result.icons.map((icon) => ({
      name: icon.name,
      source: icon.source,
    })),
  }
}

export function generateSite(): SiteOutput {
  const store = new SiteSourcesStore(ROOT)
  const lock = store.readLock()
  if (!lock)
    throw new Error(
      "upstream/site/lock.json is missing; run `bun run upstream:sync`."
    )
  const output: SiteOutput = {
    files: new Map(),
    missing: [],
    stale: [],
    warnings: [],
  }
  const icons: IconUse[] = []
  const manifest: SiteManifest = {
    commit: lock.commit,
    examples: {},
    create: [],
  }

  const components = store.list("docs", ".mdx")
  const context: DocsContext = {
    components: new Set(components),
    pages: new Set(
      readdirSync(path.join(SITE_DIR, "content", "docs")).map((file) =>
        file.replace(/\.mdx$/, "")
      )
    ),
  }

  for (const component of components) {
    const mdx = store.read(`docs/${component}.mdx`)
    const docs = transformDocs(component, mdx, context)
    output.files.set(`docs/${component}.mdx`, docs.text)
    icons.push(...docs.icons)
    for (const name of previewNames(mdx)) {
      if (manifest.examples[name]) continue
      const skipped = SKIPPED[name]
      if (skipped) {
        manifest.examples[name] = { component, skipped }
        continue
      }
      const source = store.readOptional(`examples/${name}.tsx`)
      if (source === null) {
        manifest.examples[name] = {
          component,
          skipped: "The example is not in the upstream snapshot.",
        }
        continue
      }
      manifest.examples[name] = { component }
      const translation = translate(name, source, output)
      if (!translation) continue
      icons.push(...translation.icons)
      const overridden = OVERRIDES[name]
      output.files.set(
        `examples/${name}.tsx`,
        format(
          `${header(`apps/v4/examples/base/${name}.tsx`, lock.commit, overridden ? [`Overridden: ${Object.keys(overridden.functions).join(", ")} (site/examples/overrides/${name}.tsx).`] : [])}\n\n${translation.text}`,
          `examples/${name}.tsx`
        )
      )
    }
  }

  for (const card of store.list("home", ".tsx")) {
    if (card === "index") continue
    const translation = translate(
      `home/${card}`,
      store.read(`home/${card}.tsx`),
      output
    )
    if (!translation) continue
    icons.push(...translation.icons)
    output.files.set(
      `home/${card}.tsx`,
      format(
        `${header(`apps/v4/app/(app)/(root)/cards/${card}.tsx`, lock.commit)}\n\n${translation.text}`,
        `home/${card}.tsx`
      )
    )
  }

  // The create page's registry examples: sections that need React and have
  // no override are left out rather than failing the build.
  for (const name of store.list("registry", ".json")) {
    const item = JSON.parse(store.read(`registry/${name}.json`)) as {
      title?: string
      files: { content: string }[]
    }
    const source = item.files[0]?.content
    if (!source) continue
    let result: ReturnType<typeof translateExample>
    try {
      result = translateExample(name, source)
    } catch (error) {
      output.warnings.push(
        `create/${name} is left out: ${error instanceof Error ? error.message : error}`
      )
      continue
    }
    const override = REGISTRY_OVERRIDES[name]
    let text = result.text
    if (override) {
      for (const [fn, sha256] of Object.entries(override.functions)) {
        const upstream = result.hashes.get(fn)
        if (!upstream) {
          output.stale.push(
            `registry/${name}#${fn}: the upstream function is gone`
          )
        } else if (upstream !== sha256) {
          output.stale.push(
            `registry/${name}#${fn}: upstream changed (now sha256 ${upstream}); review the override`
          )
        }
      }
      text = applyOverride(
        text,
        readFileSync(
          path.join(SITE_DIR, "examples", "registry-overrides", `${name}.tsx`),
          "utf8"
        ),
        Object.keys(override.functions)
      )
    }
    const uncovered = result.issues.filter(
      (issue) => !override?.functions[issue.name]
    )
    for (const issue of uncovered) {
      output.warnings.push(
        `create/${name}#${issue.name} is left out (sha256 ${issue.sha256}): ${issue.reasons.join("; ")}`
      )
    }
    const dropped = uncovered.map((issue) => issue.name)
    if (dropped.length > 0) text = dropFunctions(text, dropped)
    if (name !== "example") {
      manifest.create.push({ name, title: item.title ?? name, dropped })
    }
    output.files.set(
      `create/${name}.tsx`,
      format(
        // Previews only: Base UI's object values (SelectItem) need not type-check.
        `${header(`registry/base-nova/${name}`, lock.commit, dropped.length > 0 ? [`Left out (needs React): ${dropped.join(", ")}.`] : [])}\n// @ts-nocheck: a preview of the create page, not code shown to users.\n\n${tidyImports(text)}`,
        `create/${name}.tsx`
      )
    )
  }

  output.files.set(
    "icons.tsx",
    format(
      buildIconsModule(
        icons,
        "// Generated by `bun run site:generate`: the icons the site's examples import; do not edit.\n// Lucide (ISC License), Tabler Icons (MIT License) and Hugeicons (MIT License) as their React packages render them."
      ),
      "icons.tsx"
    )
  )
  output.files.set(
    "manifest.json",
    format(`${JSON.stringify(manifest, null, 2)}\n`, "manifest.json")
  )
  return output
}

/** Files under `site/generated/` that `output` does not produce. */
export function staleFiles(output: SiteOutput): string[] {
  const walk = (dir: string): string[] =>
    existsSync(dir)
      ? readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
          const full = path.join(dir, entry.name)
          return entry.isDirectory()
            ? walk(full)
            : [path.relative(GENERATED_DIR, full)]
        })
      : []
  return walk(GENERATED_DIR).filter((file) => !output.files.has(file))
}

export function removeFiles(files: string[]): void {
  for (const file of files) rmSync(path.join(GENERATED_DIR, file))
}
