import type { GeneratorConfig } from "./generator/src/config"

export const config: GeneratorConfig = {
  repository: "supermomonga/shadcnui-hono-jsx",
  style: "base-nova",
  registryBaseUrl: "https://ui.shadcn.com/r",
  themeUrl:
    "https://ui.shadcn.com/init?base=base&style=nova&baseColor=neutral&theme=neutral&iconLibrary=lucide&font=geist&rtl=false&menuAccent=subtle&menuColor=default&radius=default",
  licenseUrl: "https://raw.githubusercontent.com/shadcn-ui/ui/main/LICENSE.md",
  trackedTypes: ["registry:ui"],
  components: [
    "accordion",
    "alert",
    "alert-dialog",
    "aspect-ratio",
    "attachment",
    "avatar",
    "badge",
    "breadcrumb",
    "bubble",
    "button",
    "button-group",
    "card",
    "checkbox",
    "collapsible",
    "combobox",
    "context-menu",
    "dialog",
    "direction",
    "drawer",
    "dropdown-menu",
    "empty",
    "field",
    "hover-card",
    "input",
    "input-group",
    "item",
    "kbd",
    "label",
    "marker",
    "menubar",
    "navigation-menu",
    "message",
    "native-select",
    "pagination",
    "popover",
    "progress",
    "radio-group",
    "scroll-area",
    "select",
    "separator",
    "sheet",
    "sidebar",
    "skeleton",
    "slider",
    "spinner",
    "switch",
    "table",
    "tabs",
    "textarea",
    "toast",
    "toggle",
    "toggle-group",
    "tooltip",
  ],
}
