import { afterEach, beforeEach, describe, expect, test } from "bun:test"
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { UsageError } from "../src/errors"
import { uniqueFiles, writeFiles } from "../src/files"
import { finalize, unsupportedOptions } from "../src/finalize"
import {
  detectPackageManager,
  installCommand,
  missingDependencies,
} from "../src/package-manager"
import { DEFAULT_VARIANT, variantCandidates, variantDir } from "../src/variants"

let dir: string

beforeEach(() => {
  dir = mkdtempSync(path.join(tmpdir(), "shj-cli-"))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

describe("writeFiles", () => {
  test("creates, keeps identical files and refuses to replace others", () => {
    writeFileSync(path.join(dir, "same.txt"), "same")
    const summary = writeFiles(
      dir,
      [
        { path: "a/new.txt", text: "new" },
        { path: "same.txt", text: "same" },
      ],
      { overwrite: false, hint: "" }
    )
    expect(summary).toEqual({
      created: ["a/new.txt"],
      updated: [],
      unchanged: ["same.txt"],
    })
    expect(() =>
      writeFiles(dir, [{ path: "same.txt", text: "other" }], {
        overwrite: false,
        hint: "Pass --overwrite.",
      })
    ).toThrow(/same\.txt[\s\S]*--overwrite/)
    expect(readFileSync(path.join(dir, "same.txt"), "utf8")).toBe("same")
  })

  test("replaces files with overwrite", () => {
    writeFileSync(path.join(dir, "x.txt"), "old")
    const summary = writeFiles(dir, [{ path: "x.txt", text: "new" }], {
      overwrite: true,
      hint: "",
    })
    expect(summary.updated).toEqual(["x.txt"])
    expect(readFileSync(path.join(dir, "x.txt"), "utf8")).toBe("new")
  })

  test("merges repeated paths only when their contents agree", () => {
    expect(
      uniqueFiles([
        { path: "a", text: "1" },
        { path: "a", text: "1" },
      ])
    ).toEqual([{ path: "a", text: "1" }])
    expect(() =>
      uniqueFiles([
        { path: "a", text: "1" },
        { path: "a", text: "2" },
      ])
    ).toThrow()
  })
})

describe("finalize", () => {
  const template =
    "// Generated by shadcnui-hono-jsx. DO NOT EDIT.\n// rest\ncode\n"
  const defaults = { iconLibrary: "lucide" } as const

  test("replaces the maintainer header line", () => {
    expect(finalize(template, { ...defaults, preset: "b0" })).toBe(
      "// Installed by shadcnui-hono-jsx for the shadcn/ui preset b0; `shadcnui-hono-jsx apply` rewrites this file.\n// rest\ncode\n"
    )
  })

  test("reports options it cannot produce yet", () => {
    expect(unsupportedOptions(defaults)).toEqual([])
    expect(unsupportedOptions({ iconLibrary: "tabler" })).toEqual([
      'iconLibrary "tabler"',
    ])
    expect(() =>
      finalize(template, { iconLibrary: "tabler", preset: "b0" })
    ).toThrow(/tabler/)
  })
})

describe("variants", () => {
  test("are looked up from the most specific to the default", () => {
    expect(variantDir(DEFAULT_VARIANT)).toBe("")
    expect(variantCandidates({ rtl: true, menuColor: "inverted" })).toEqual([
      "rtl_menu-inverted",
      "rtl",
      "menu-inverted",
      "",
    ])
    expect(variantCandidates({ rtl: false, menuColor: "default" })).toEqual([
      "",
    ])
  })
})

describe("package manager", () => {
  test("detects the nearest lockfile and falls back to npm", () => {
    const app = path.join(dir, "app")
    mkdirSync(app)
    expect(detectPackageManager(app)).toBe("npm")
    writeFileSync(path.join(dir, "pnpm-lock.yaml"), "")
    expect(detectPackageManager(app)).toBe("pnpm")
    writeFileSync(path.join(app, "bun.lock"), "")
    expect(detectPackageManager(app)).toBe("bun")
  })

  test("lists packages that package.json does not have yet", () => {
    writeFileSync(
      path.join(dir, "package.json"),
      JSON.stringify({ dependencies: { cn: "1" }, devDependencies: { x: "1" } })
    )
    expect(
      missingDependencies(dir, ["x", "tw-animate-css", "cn", "a"])
    ).toEqual(["a", "tw-animate-css"])
    expect(() => missingDependencies(path.join(dir, "none"), ["a"])).toThrow(
      UsageError
    )
  })

  test("builds install commands", () => {
    expect(installCommand("npm", ["a"])).toEqual(["npm", "install", "a"])
    expect(installCommand("bun", ["a", "b"])).toEqual(["bun", "add", "a", "b"])
  })
})
