import { derivedNoticeLines, iconNoticeLines } from "../licenses"

export interface HeaderInput {
  name: string
  style: string
  url: string
  contentSha256: string
  upstreamCommit: string | null
  mode: "generated" | "adapter"
  /** Canonical names of inlined Lucide icons, and the pinned lucide version. */
  icons?: { names: string[]; version: string }
  /** Client scripts the component needs (docs/adr/0025). */
  scripts?: string[]
}

/**
 * Short machine-readable header for generated components. It contains no
 * timestamps so regeneration is byte-for-byte deterministic. The full license
 * travels as a separate notice file installed with every registry item.
 */
export function renderHeader(input: HeaderInput): string {
  return [
    `Generated by shadcnui-hono-jsx. DO NOT EDIT; run \`bun run generate ${input.name}\`.`,
    `upstream: shadcn/ui ${input.style}/${input.name} (${input.url})`,
    `upstream-revision: sha256:${input.contentSha256}; shadcn-ui/ui@${input.upstreamCommit ?? "unknown"}`,
    `mode: ${input.mode}`,
    ...(input.scripts && input.scripts.length > 0
      ? [
          `client: ${input.scripts.map((name) => `<script type="module" src="/shadcn/${name}.js">`).join(" ")} (public/shadcn/)`,
        ]
      : []),
    ...derivedNoticeLines(),
    ...(input.icons && input.icons.names.length > 0
      ? iconNoticeLines(input.icons.names, input.icons.version)
      : []),
  ]
    .map((line) => `// ${line}\n`)
    .join("")
}

export interface LiteHeaderInput {
  name: string
  /** The hand-written source in the repository. */
  source: string
  style: string
  basedOn: { name: string; url: string; sha256: string }[]
  icons?: { names: string[]; version: string }
}

/** Header of a lite alternative (docs/adr/0028): hand-written, not translated from upstream. */
export function renderLiteHeader(input: LiteHeaderInput): string {
  return [
    `Generated by shadcnui-hono-jsx from ${input.source}. DO NOT EDIT; run \`bun run generate ${input.name}\`.`,
    `lite: a hand-written alternative that approximates shadcn/ui without JavaScript; not a port of upstream code.`,
    ...input.basedOn.map(
      (base) =>
        `based-on: shadcn/ui ${input.style}/${base.name} (${base.url}) sha256:${base.sha256}`
    ),
    ...derivedNoticeLines(),
    ...(input.icons && input.icons.names.length > 0
      ? iconNoticeLines(input.icons.names, input.icons.version)
      : []),
  ]
    .map((line) => `// ${line}\n`)
    .join("")
}
