import { derivedNoticeLines, iconNoticeLines } from "../licenses"

export interface HeaderInput {
  name: string
  style: string
  url: string
  contentSha256: string
  upstreamCommit: string | null
  mode: "generated" | "adapter"
  /** Canonical names of inlined Lucide icons, and the pinned lucide version. */
  icons?: { names: string[]; version: string }
  /** Client scripts the component needs (docs/adr/0025). */
  scripts?: string[]
}

/**
 * Short machine-readable header for generated components. It contains no
 * timestamps so regeneration is byte-for-byte deterministic. The full license
 * travels as a separate notice file installed with every registry item.
 */
export function renderHeader(input: HeaderInput): string {
  return [
    `Generated by shadcnui-hono-jsx. DO NOT EDIT; run \`bun run generate ${input.name}\`.`,
    `upstream: shadcn/ui ${input.style}/${input.name} (${input.url})`,
    `upstream-revision: sha256:${input.contentSha256}; shadcn-ui/ui@${input.upstreamCommit ?? "unknown"}`,
    `mode: ${input.mode}`,
    ...(input.scripts && input.scripts.length > 0
      ? [
          `client: ${input.scripts.map((name) => `<script type="module" src="/shadcn/${name}.js">`).join(" ")} (public/shadcn/)`,
        ]
      : []),
    ...derivedNoticeLines(),
    ...(input.icons && input.icons.names.length > 0
      ? iconNoticeLines(input.icons.names, input.icons.version)
      : []),
  ]
    .map((line) => `// ${line}\n`)
    .join("")
}
