export interface HeaderInput {
  name: string
  style: string
  url: string
  contentSha256: string
  upstreamCommit: string | null
  mode: "generated" | "adapter"
  repository: string
}

/**
 * Short machine-readable header for generated components. It contains no
 * timestamps so regeneration is byte-for-byte deterministic.
 */
export function renderHeader(input: HeaderInput): string {
  return [
    `// Generated by shadcnui-hono-jsx. DO NOT EDIT; run \`bun run generate ${input.name}\`.`,
    `// upstream: shadcn/ui ${input.style}/${input.name} (${input.url})`,
    `// upstream-revision: sha256:${input.contentSha256}; shadcn-ui/ui@${input.upstreamCommit ?? "unknown"}`,
    `// mode: ${input.mode}`,
    `// Derived from shadcn/ui, Copyright (c) 2023 shadcn, MIT License. See https://github.com/${input.repository}/blob/main/THIRD_PARTY_LICENSES.md`,
    "",
  ].join("\n")
}
