// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate aspect-ratio`.
// upstream: shadcn/ui base-nova/aspect-ratio (https://ui.shadcn.com/r/styles/base-nova/aspect-ratio.json)
// upstream-revision: sha256:3d25d73f77dedf7c11f1e089114b9c1ed142f2aa44c9c3398c06f7d046809ea9; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: generated
// Derived from shadcn/ui. Copyright (c) 2023 shadcn.
// Original additions and modifications: Copyright (c) 2026 supermomonga.
// SPDX-License-Identifier: MIT
// Full license: LICENSE-shadcnui-hono-jsx.txt at the project root.

import { cn } from "cn"
import type { CSSProperties, JSX } from "hono/jsx"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<T extends keyof JSX.IntrinsicElements> =
  JSX.IntrinsicElements[T] & {
    class?: string | undefined
    className?: never
    render?: never
    asChild?: never
  }

function AspectRatio({
  ratio,
  class: className,
  ...props
}: ComponentProps<"div"> & { ratio: number }) {
  return (
    <div
      data-slot="aspect-ratio"
      style={
        {
          "--ratio": String(ratio),
        } as CSSProperties
      }
      class={cn("relative aspect-(--ratio)", className)}
      {...props}
    />
  )
}

export { AspectRatio }
