// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate collapsible`.
// upstream: shadcn/ui base-nova/collapsible (https://ui.shadcn.com/r/styles/base-nova/collapsible.json)
// upstream-revision: sha256:3b60084afb5667cb11a4f7b40bbe66585cdc70f2cb26d698e551f055cda91a4d; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: generated
// Derived from shadcn/ui. Copyright (c) 2023 shadcn.
// Original additions and modifications: Copyright (c) 2026 supermomonga.
// SPDX-License-Identifier: MIT
// Full license: LICENSE-shadcnui-hono-jsx.txt at the project root.

import type { JSX, JSXNode } from "hono/jsx"
import { isValidElement } from "hono/jsx"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<
  T extends keyof JSX.IntrinsicElements,
  Render = never,
> = JSX.IntrinsicElements[T] & {
  class?: string | undefined
  className?: never
  render?: Render
  asChild?: never
}

type CollapsibleRootProps = ComponentProps<"details"> & {
  defaultOpen?: boolean | undefined
}

/**
 * A native `<details>`: `<CollapsibleTrigger>` must be its first child (the
 * `<summary>`), and every other child is hidden while it is closed.
 */
function CollapsibleRootElement({
  defaultOpen = false,
  open,
  children,
  ...props
}: CollapsibleRootProps) {
  const [first] = [children]
    .flat(Number.POSITIVE_INFINITY)
    .filter(
      (child) =>
        child !== null && child !== undefined && child !== false && child !== ""
    )
  if (!isValidElement(first) || (first as JSXNode).tag !== CollapsibleTrigger) {
    throw new Error(
      "<CollapsibleTrigger> must be the first child of <Collapsible>"
    )
  }
  return (
    <details open={(open ?? defaultOpen) || undefined} {...props}>
      {children}
    </details>
  )
}

function CollapsibleTriggerElement({
  class: className,
  ...props
}: ComponentProps<"summary">) {
  return (
    <summary
      class={
        className
          ? `list-none [&::-webkit-details-marker]:hidden ${className}`
          : "list-none [&::-webkit-details-marker]:hidden"
      }
      {...props}
    />
  )
}

function Collapsible({ ...props }: CollapsibleRootProps) {
  return <CollapsibleRootElement data-slot="collapsible" {...props} />
}

function CollapsibleTrigger({ ...props }: ComponentProps<"summary">) {
  return (
    <CollapsibleTriggerElement data-slot="collapsible-trigger" {...props} />
  )
}

function CollapsibleContent({ ...props }: ComponentProps<"div">) {
  return <div data-slot="collapsible-content" {...props} />
}

export { Collapsible, CollapsibleContent, CollapsibleTrigger }
