// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate dialog`.
// upstream: shadcn/ui base-nova/dialog (https://ui.shadcn.com/r/styles/base-nova/dialog.json)
// upstream-revision: sha256:356e4775f1edfd051ace0678b6a23bffbce042045f470971755438a7c199dafe; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: adapter
// Derived from shadcn/ui. Copyright (c) 2023 shadcn.
// Original additions and modifications: Copyright (c) 2026 supermomonga.
// SPDX-License-Identifier: MIT
// Full license: LICENSE-shadcnui-hono-jsx.txt at the project root.
// Icons: lucide@1.48.0 (x). Copyright (c) 2026 Lucide Icons and Contributors. ISC License (see LICENSE-shadcnui-hono-jsx.txt).

import { cn } from "cn"
import type { Child, JSX, JSXNode } from "hono/jsx"
import {
  cloneElement,
  createContext,
  isValidElement,
  useContext,
  useId,
} from "hono/jsx"
import { Button } from "./button"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<
  T extends keyof JSX.IntrinsicElements | "svg",
  Render = never,
> = (T extends keyof JSX.IntrinsicElements
  ? JSX.IntrinsicElements[T]
  : JSX.HTMLAttributes) & {
  class?: string | undefined
  className?: never
  render?: Render
  asChild?: never
}

/** An element (or a function returning one) that replaces the default element, as in Base UI. */
type RenderProp = Child | ((props: Record<string, unknown>) => Child)

/**
 * Renders `render` in place of `element`, merging props like Base UI's
 * mergeProps: the render element's props win, classes are combined (the render
 * element's first) and styles are merged. `type` only applies to button and
 * input targets.
 */
function renderElement<Element>(
  element: Element,
  render: RenderProp | undefined
): Element {
  if (render === undefined) return element
  const own: Record<string, unknown> = {
    ...(element as unknown as JSXNode).props,
  }
  if (typeof render === "function") return render(own) as Element
  if (!isValidElement(render)) {
    throw new Error("render must be a JSX element or a function returning one")
  }
  const target = render as JSXNode
  const merged: Record<string, unknown> = { ...own }
  for (const [key, value] of Object.entries(target.props)) {
    if (key === "class" || key === "className") {
      merged.class = [value, own.class].filter(Boolean).join(" ")
    } else if (key === "style" && isObject(value) && isObject(own.style)) {
      merged.style = { ...own.style, ...value }
    } else {
      merged[key] = value
    }
  }
  if (
    typeof target.tag === "string" &&
    !["button", "input"].includes(target.tag)
  ) {
    if (!("type" in target.props)) delete merged.type
  }
  const { children, ...props } = merged
  return cloneElement(
    target,
    props,
    ...(children === undefined ? [] : [children as Child].flat())
  ) as Element
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null
}

interface DialogContextValue {
  id: string
  titleId: string
  descriptionId: string
}

const DialogContext = createContext<DialogContextValue | null>(null)

function useDialogContext(part: string): DialogContextValue {
  const context = useContext(DialogContext)
  if (!context) throw new Error(`<${part}> must be used within <Dialog>`)
  return context
}

/**
 * Connects the trigger, the native `<dialog>`, its title and description.
 * Opening and closing use Invoker Commands, so no JavaScript is shipped.
 */
function Dialog({
  id,
  children,
}: {
  id?: string | undefined
  children?: Child
}) {
  const generated = useId()
  const dialogId = id ?? `dialog${generated.replaceAll(":", "-")}`
  return (
    <DialogContext.Provider
      value={{
        id: dialogId,
        titleId: `${dialogId}-title`,
        descriptionId: `${dialogId}-description`,
      }}
    >
      {children}
    </DialogContext.Provider>
  )
}

function DialogTrigger({
  type = "button",
  render,
  ...props
}: ComponentProps<"button", RenderProp>) {
  const { id } = useDialogContext("DialogTrigger")
  return renderElement(
    <button
      type={type}
      command="show-modal"
      commandfor={id}
      aria-haspopup="dialog"
      data-slot="dialog-trigger"
      {...props}
    />,
    render
  )
}

/** The native dialog renders in the top layer, so no portal is needed. */
function DialogPortal({ children }: { children?: Child }) {
  return <>{children}</>
}

function DialogClose({
  type = "button",
  render,
  ...props
}: ComponentProps<"button", RenderProp>) {
  const { id } = useDialogContext("DialogClose")
  return renderElement(
    <button
      type={type}
      command="close"
      commandfor={id}
      data-slot="dialog-close"
      {...props}
    />,
    render
  )
}

/**
 * The native dialog draws its overlay with `::backdrop`, styled by
 * DialogContent, so this renders nothing. Kept for API compatibility.
 */
function DialogOverlay(_props: ComponentProps<"div">) {
  return null
}

function DialogContent({
  class: className,
  children,
  showCloseButton = true,
  ...props
}: ComponentProps<"dialog"> & {
  showCloseButton?: boolean
}) {
  const { id, titleId, descriptionId } = useDialogContext("DialogContent")
  return (
    <dialog
      id={id}
      closedby="any"
      aria-labelledby={titleId}
      aria-describedby={descriptionId}
      data-slot="dialog-content"
      class={cn(
        "backdrop:bg-black/10 backdrop:duration-100 supports-backdrop-filter:backdrop:backdrop-blur-xs open:backdrop:animate-in open:backdrop:fade-in-0",
        "fixed top-1/2 left-1/2 z-50 grid w-full max-w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 gap-4 rounded-xl bg-popover p-4 text-sm text-popover-foreground ring-1 ring-foreground/10 duration-100 outline-none sm:max-w-sm open:animate-in open:fade-in-0 open:zoom-in-95 not-open:hidden",
        className
      )}
      {...props}
    >
      {children}
      {showCloseButton && (
        <Button
          variant="ghost"
          class="absolute top-2 right-2"
          size="icon-sm"
          data-slot="dialog-close"
          command="close"
          commandfor={id}
        >
          <XIcon />
          <span class="sr-only">Close</span>
        </Button>
      )}
    </dialog>
  )
}

function DialogHeader({ class: className, ...props }: ComponentProps<"div">) {
  return (
    <div
      data-slot="dialog-header"
      class={cn("flex flex-col gap-2", className)}
      {...props}
    />
  )
}

function DialogFooter({
  class: className,
  showCloseButton = false,
  children,
  ...props
}: ComponentProps<"div"> & {
  showCloseButton?: boolean
}) {
  const id = useContext(DialogContext)?.id
  if (showCloseButton && !id) {
    throw new Error(
      "<DialogFooter showCloseButton> must be used within <Dialog>"
    )
  }
  return (
    <div
      data-slot="dialog-footer"
      class={cn(
        "-mx-4 -mb-4 flex flex-col-reverse gap-2 rounded-b-xl border-t bg-muted/50 p-4 sm:flex-row sm:justify-end",
        className
      )}
      {...props}
    >
      {children}
      {showCloseButton && (
        <Button variant="outline" command="close" commandfor={id}>
          Close
        </Button>
      )}
    </div>
  )
}

function DialogTitle({ class: className, ...props }: ComponentProps<"h2">) {
  return (
    <h2
      id={useContext(DialogContext)?.titleId}
      data-slot="dialog-title"
      class={cn("font-heading text-base leading-none font-medium", className)}
      {...props}
    />
  )
}

function DialogDescription({
  class: className,
  ...props
}: ComponentProps<"p">) {
  return (
    <p
      id={useContext(DialogContext)?.descriptionId}
      data-slot="dialog-description"
      class={cn(
        "text-sm text-muted-foreground *:[a]:underline *:[a]:underline-offset-3 *:[a]:hover:text-foreground",
        className
      )}
      {...props}
    />
  )
}
/** Like lucide-react, icons are hidden from assistive technology unless labelled. */
function hasA11yProp(props: object): boolean {
  return Object.keys(props).some(
    (key) => key.startsWith("aria-") || key === "role" || key === "title"
  )
}

/** Lucide `x` icon, inlined (ISC License, see LICENSE-shadcnui-hono-jsx.txt). */
function XIcon({
  class: className,
  children,
  ...props
}: ComponentProps<"svg">) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      class={cn("lucide lucide-x", className)}
      aria-hidden={children || hasA11yProp(props) ? undefined : "true"}
      {...props}
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
      {children}
    </svg>
  )
}

export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
}
