// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate separator`.
// upstream: shadcn/ui base-nova/separator (https://ui.shadcn.com/r/styles/base-nova/separator.json)
// upstream-revision: sha256:e331ea0c4e835484b0a3fcefa172a884864bdc0e1bfe39d12c119c66ad4e3195; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: generated
// Derived from shadcn/ui, Copyright (c) 2023 shadcn, MIT License. See https://github.com/supermomonga/shadcnui-hono-jsx/blob/main/THIRD_PARTY_LICENSES.md

import { cn } from "cn"
import type { JSX } from "hono/jsx"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<T extends keyof JSX.IntrinsicElements> =
  JSX.IntrinsicElements[T] & {
    class?: string | undefined
    className?: never
    render?: never
    asChild?: never
  }

function Separator({
  class: className,
  orientation = "horizontal",
  ...props
}: ComponentProps<"div"> & {
  orientation?: "horizontal" | "vertical" | undefined
}) {
  return (
    <div
      data-slot="separator"
      aria-orientation={orientation}
      data-orientation={orientation}
      class={cn(
        "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
        className
      )}
      role="separator"
      {...props}
    />
  )
}

export { Separator }
