// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate skeleton`.
// upstream: shadcn/ui base-nova/skeleton (https://ui.shadcn.com/r/styles/base-nova/skeleton.json)
// upstream-revision: sha256:97a90c6788815d37eda6dad532aa207e5a878d22b4d5f9e91c16bb2f4bc2f341; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: generated
// Derived from shadcn/ui, Copyright (c) 2023 shadcn, MIT License. See https://github.com/supermomonga/shadcnui-hono-jsx/blob/main/THIRD_PARTY_LICENSES.md

import { cn } from "cn"
import type { JSX } from "hono/jsx"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<T extends keyof JSX.IntrinsicElements> =
  JSX.IntrinsicElements[T] & {
    class?: string | undefined
    className?: never
    render?: never
    asChild?: never
  }

function Skeleton({ class: className, ...props }: ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      class={cn("animate-pulse rounded-md bg-muted", className)}
      {...props}
    />
  )
}

export { Skeleton }
