// Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate toggle-group`.
// upstream: shadcn/ui base-nova/toggle-group (https://ui.shadcn.com/r/styles/base-nova/toggle-group.json)
// upstream-revision: sha256:09efc4edf7c75c96046af788d137af36d6bf2d386f9b9dbf5a6349c783ace321; shadcn-ui/ui@98a1fe67b439324ddc857f47fbdce056600a4329
// mode: generated
// Derived from shadcn/ui. Copyright (c) 2023 shadcn.
// Original additions and modifications: Copyright (c) 2026 supermomonga.
// SPDX-License-Identifier: MIT
// Full license: LICENSE-shadcnui-hono-jsx.txt at the project root.

import type { VariantProps } from "class-variance-authority"
import { cn } from "cn"
import type { CSSProperties, JSX } from "hono/jsx"
import { createContext, useContext, useId } from "hono/jsx"

import { toggleVariants } from "./toggle"

/** Props of the intrinsic element `T`, following Hono JSX conventions (`class`, no `render`/`asChild`). */
type ComponentProps<
  T extends keyof JSX.IntrinsicElements,
  Render = never,
> = JSX.IntrinsicElements[T] & {
  class?: string | undefined
  className?: never
  render?: Render
  asChild?: never
}

type ToggleGroupRootProps = ComponentProps<"div"> & {
  name?: string | undefined
  /** Values of the items that are pressed on load. */
  defaultValue?: readonly string[] | undefined
  /** Lets several items be pressed; otherwise the items are radios. */
  multiple?: boolean | undefined
  disabled?: boolean | undefined
}

function ToggleGroupRootElement({
  name,
  defaultValue = [],
  multiple = false,
  disabled = false,
  ...props
}: ToggleGroupRootProps) {
  const id = useId().replaceAll(":", "-")
  return (
    <ToggleGroupItemContext.Provider
      value={{
        name: name ?? `toggle-group${id}`,
        multiple,
        values: defaultValue,
        disabled,
      }}
    >
      <div role="group" {...props} />
    </ToggleGroupItemContext.Provider>
  )
}
const CONTROL_INPUT_PROPS = new Set([
  "id",
  "name",
  "value",
  "disabled",
  "required",
  "form",
  "autofocus",
])

/** Splits props between the native input (form and ARIA attributes) and the styled root. */
function splitControlProps(
  props: Record<string, unknown>
): [Record<string, unknown>, Record<string, unknown>] {
  const input: Record<string, unknown> = {}
  const root: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(props)) {
    if (CONTROL_INPUT_PROPS.has(key) || key.startsWith("aria-"))
      input[key] = value
    else root[key] = value
  }
  return [input, root]
}

type ToggleRootProps = ComponentProps<"label"> & {
  pressed?: boolean | undefined
  defaultPressed?: boolean | undefined
  disabled?: boolean | undefined
  name?: string | undefined
  value?: string | undefined
  form?: string | undefined
}

/** Set by a toggle group: its items are radios (or checkboxes with `multiple`) sharing a name. */
interface ToggleGroupItemContextValue {
  name: string
  multiple: boolean
  values: readonly string[]
  disabled: boolean
}

const ToggleGroupItemContext =
  createContext<ToggleGroupItemContextValue | null>(null)

/** A label around a visually hidden checkbox: pressing toggles it without JavaScript. */
function ToggleRootElement({
  pressed,
  defaultPressed,
  value,
  disabled,
  children,
  ...props
}: ToggleRootProps) {
  const group = useContext(ToggleGroupItemContext)
  const [input, root] = splitControlProps(props)
  const isPressed = group
    ? value !== undefined && group.values.includes(value)
    : (pressed ?? defaultPressed ?? false)
  return (
    <label {...root}>
      <input
        type={group && !group.multiple ? "radio" : "checkbox"}
        name={group?.name}
        value={value}
        checked={isPressed || undefined}
        disabled={group?.disabled || disabled || undefined}
        class="peer sr-only"
        {...input}
      />
      {children}
    </label>
  )
}

const ToggleGroupContext = createContext<
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }
>({
  size: "default",
  variant: "default",
  spacing: 2,
  orientation: "horizontal",
})

function ToggleGroup({
  class: className,
  variant,
  size,
  spacing = 2,
  orientation = "horizontal",
  children,
  ...props
}: ToggleGroupRootProps &
  VariantProps<typeof toggleVariants> & {
    spacing?: number
    orientation?: "horizontal" | "vertical"
  }) {
  return (
    <ToggleGroupRootElement
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      data-spacing={spacing}
      data-orientation={orientation}
      style={{ "--gap": String(spacing) } as CSSProperties}
      class={cn(
        "group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] rounded-lg data-[size=sm]:rounded-[min(var(--radius-md),10px)] data-vertical:flex-col data-vertical:items-stretch",
        className
      )}
      {...props}
    >
      <ToggleGroupContext.Provider
        value={{ variant, size, spacing, orientation }}
      >
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupRootElement>
  )
}

function ToggleGroupItem({
  class: className,
  children,
  variant = "default",
  size = "default",
  ...props
}: ToggleRootProps & VariantProps<typeof toggleVariants>) {
  const context = useContext(ToggleGroupContext)

  return (
    <ToggleRootElement
      data-slot="toggle-group-item"
      data-variant={context.variant || variant}
      data-size={context.size || size}
      data-spacing={context.spacing}
      class={cn(
        "shrink-0 group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-2 has-focus:z-10 has-focus-visible:z-10 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-end]:pr-1.5 group-data-[spacing=0]/toggle-group:has-data-[icon=inline-start]:pl-1.5 group-data-horizontal/toggle-group:data-[spacing=0]:first:rounded-l-lg group-data-vertical/toggle-group:data-[spacing=0]:first:rounded-t-lg group-data-horizontal/toggle-group:data-[spacing=0]:last:rounded-r-lg group-data-vertical/toggle-group:data-[spacing=0]:last:rounded-b-lg group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t",
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </ToggleRootElement>
  )
}

export { ToggleGroup, ToggleGroupItem }
