import { describe, expect, test } from "bun:test"
import { existsSync, readdirSync, readFileSync } from "node:fs"
import path from "node:path"
import { readTemplate } from "../../cli/src/catalog"
import { TEMPLATES_DIR } from "../../cli/src/paths"
import {
  MENU_COLORS,
  type Variant,
  variantCandidates,
  variantDir,
} from "../../cli/src/variants"
import { config } from "../../generator.config"
import { LITE_COMPONENTS } from "../src/lite"
import {
  applyVariant,
  candidateVariants,
  hasMenuMarkers,
} from "../src/variants"

const ALL_VARIANTS: Variant[] = [false, true].flatMap((rtl) =>
  MENU_COLORS.map((menuColor) => ({ rtl, menuColor }))
)
const names = [...config.components, ...Object.keys(LITE_COMPONENTS)]
const withoutVariantLine = (text: string) =>
  text.replace(/^\/\/ variant: .*\n/m, "")

describe("template variants (docs/adr/0030)", () => {
  test.each(config.styles.map((style) => [style] as const))(
    "%s stores only variants that differ from the template they fall back to",
    (style) => {
      for (const variant of ALL_VARIANTS) {
        const dir = variantDir(variant)
        if (!dir) continue
        const directory = path.join(TEMPLATES_DIR, style, dir)
        if (!existsSync(directory)) continue
        for (const file of readdirSync(directory)) {
          const name = file.replace(/\.tsx$/, "")
          expect(names).toContain(name)
          const text = readFileSync(path.join(directory, file), "utf8")
          expect(text).toContain(`// variant: ${dir}\n`)
          const [, fallback] = variantCandidates(variant).filter(
            (candidate) =>
              candidate === dir ||
              existsSync(path.join(TEMPLATES_DIR, style, candidate, file))
          )
          const other = readFileSync(
            path.join(TEMPLATES_DIR, style, fallback ?? "", file),
            "utf8"
          )
          expect(withoutVariantLine(text)).not.toBe(withoutVariantLine(other))
        }
      }
    }
  )

  test("every option value finds a template for every component", () => {
    for (const style of config.styles) {
      for (const variant of ALL_VARIANTS) {
        for (const name of names) {
          expect(readTemplate(style, name, variant)).toContain(
            "Generated by shadcnui-hono-jsx"
          )
        }
      }
    }
  })

  test("menu colors apply to components with menu markers", () => {
    const menus = config.components.filter((name) =>
      hasMenuMarkers(
        readFileSync(
          path.join("upstream", config.style, "items", `${name}.json`),
          "utf8"
        )
      )
    )
    expect(menus).toEqual([
      "combobox",
      "context-menu",
      "dropdown-menu",
      "menubar",
      "select",
    ])
    for (const name of menus) {
      expect(
        readTemplate(config.style, name, {
          rtl: false,
          menuColor: "inverted",
        })
      ).toContain("// variant: menu-inverted\n")
    }
  })
})

describe("applyVariant", () => {
  const source = `import { cn } from "@/lib/utils"
function Content({ side = "right", className }: { side?: string; className?: string }) {
  return <div className={cn("cn-menu-target cn-menu-translucent ml-2 bg-popover", className)} />
}
function ContextMenuSubContent({ side = "right" }: { side?: string }) {
  return <Content side={side} />
}
`

  test("resolves menu markers with the shadcn CLI's transformMenu", async () => {
    const inverted = await applyVariant(source, {
      rtl: false,
      menuColor: "inverted-translucent",
    })
    expect(inverted).toMatch(/"dark .*bg-popover\/70/)
    expect(inverted).not.toContain("cn-menu-")
  })

  test("applies the shadcn CLI's RTL transform after the menu one", async () => {
    const rtl = await applyVariant(source, { rtl: true, menuColor: "default" })
    expect(rtl).toContain("ms-2")
    expect(rtl).toContain('side = "inline-end"')
    expect(rtl).toContain("cn-menu-target")
  })

  test("candidates cover menu colors only for components with menu markers", () => {
    expect(candidateVariants("plain").map(variantDir)).toEqual(["rtl"])
    expect(candidateVariants("cn-menu-target").map(variantDir)).toEqual([
      "menu-inverted",
      "menu-default-translucent",
      "menu-inverted-translucent",
      "rtl",
      "rtl_menu-inverted",
      "rtl_menu-default-translucent",
      "rtl_menu-inverted-translucent",
    ])
  })
})
