import { derivedNoticeLines, vendoredNoticeLines } from "../licenses"
import type { CssVars, ThemeItem } from "../upstream/types"

/** Radius scale the shadcn CLI adds to `@theme inline` for a `radius` variable. */
export const RADIUS_SCALE: readonly [string, string][] = [
  ["sm", "calc(var(--radius) * 0.6)"],
  ["md", "calc(var(--radius) * 0.8)"],
  ["lg", "var(--radius)"],
  ["xl", "calc(var(--radius) * 1.4)"],
  ["2xl", "calc(var(--radius) * 1.8)"],
  ["3xl", "calc(var(--radius) * 2.2)"],
  ["4xl", "calc(var(--radius) * 2.6)"],
]

/** Imports in upstream `css` that must point at files this project ships. */
export const IMPORT_REWRITES: Readonly<Record<string, string>> = {
  '@import "shadcn/tailwind.css"': '@import "./tailwind.css"',
}

const COLOR_VALUE =
  /^(oklch|oklab|lch|lab|hsl|hsla|rgb|rgba|hwb|color)\(|^#[0-9a-f]{3,8}$/i

const indent = (depth: number) => "  ".repeat(depth)
const varName = (key: string) => `--${key.replace(/^--/, "")}`

function declarations(vars: CssVars, depth: number): string[] {
  return Object.entries(vars).map(
    ([key, value]) => `${indent(depth)}${varName(key)}: ${value};`
  )
}

/**
 * Serializes the upstream `css` object: `{}` values become statements
 * (`@import "x";`, `@apply a b;`), objects become blocks, strings become
 * declarations.
 */
export function serializeCss(
  css: Record<string, unknown>,
  depth = 0
): string[] {
  const lines: string[] = []
  for (const [key, value] of Object.entries(css)) {
    const rewritten = IMPORT_REWRITES[key] ?? key
    if (typeof value === "string") {
      lines.push(`${indent(depth)}${rewritten}: ${value};`)
    } else if (
      value &&
      typeof value === "object" &&
      Object.keys(value).length > 0
    ) {
      lines.push(`${indent(depth)}${rewritten} {`)
      lines.push(...serializeCss(value as Record<string, unknown>, depth + 1))
      lines.push(`${indent(depth)}}`)
    } else if (value && typeof value === "object") {
      lines.push(`${indent(depth)}${rewritten};`)
    } else {
      throw new Error(`Unsupported css value for "${key}"`)
    }
  }
  return lines
}

/** The `@theme inline` mappings the shadcn CLI derives from light/dark variables. */
export function themeMappings(theme: ThemeItem): string[] {
  const { light = {}, dark = {} } = theme.cssVars
  const keys = [...new Set([...Object.keys(light), ...Object.keys(dark)])]
  const lines: string[] = []
  for (const key of keys) {
    const value = light[key] ?? dark[key] ?? ""
    const name = key.replace(/^--/, "")
    if (name === "radius") {
      for (const [size, expression] of RADIUS_SCALE) {
        lines.push(`${indent(1)}--radius-${size}: ${expression};`)
      }
    } else if (COLOR_VALUE.test(value)) {
      lines.push(`${indent(1)}--color-${name}: var(--${name});`)
    } else {
      lines.push(`${indent(1)}--${name}: var(--${name});`)
    }
  }
  lines.push(...declarations(theme.cssVars.theme ?? {}, 1))
  return lines
}

export interface ThemeHeader {
  url: string
  sha256: string
}

function header(lines: string[]): string {
  return [
    "/*",
    ...lines.map((line) => (line ? ` * ${line}` : " *")),
    " */",
  ].join("\n")
}

/**
 * Builds `theme.css` the way `shadcn init` writes a Tailwind v4 stylesheet for
 * the upstream theme, minus the `@import "tailwindcss"` that the consuming
 * project owns.
 */
export function buildThemeCss(theme: ThemeItem, source: ThemeHeader): string {
  const css = { ...(theme.css ?? {}) }
  const imports = Object.keys(css).filter((key) => key.startsWith("@import"))
  const rest = Object.fromEntries(
    Object.entries(css).filter(([key]) => !key.startsWith("@import"))
  )
  const { light = {}, dark = {} } = theme.cssVars
  const sections = [
    header([
      "Generated by shadcnui-hono-jsx. DO NOT EDIT; run `bun run generate`.",
      `upstream: shadcn/ui ${theme.name} theme (${source.url})`,
      `upstream-revision: sha256:${source.sha256}`,
      ...derivedNoticeLines(),
      "",
      "Usage: import after Tailwind CSS, e.g.",
      '  @import "tailwindcss";',
      '  @import "./styles/shadcn/theme.css";',
    ]),
    serializeCss(Object.fromEntries(imports.map((key) => [key, {}]))).join(
      "\n"
    ),
    "@custom-variant dark (&:is(.dark *));",
    [":root {", ...declarations(light, 1), "}"].join("\n"),
    [".dark {", ...declarations(dark, 1), "}"].join("\n"),
    ["@theme inline {", ...themeMappings(theme), "}"].join("\n"),
    serializeCss(rest).join("\n"),
  ]
  return `${sections.filter((s) => s.length > 0).join("\n\n")}\n`
}

/** The vendored `shadcn/tailwind.css` with a provenance header. */
export function buildVendoredTailwindCss(
  text: string,
  source: {
    package: string
    version: string
    file: string
    sha256: string
  }
): string {
  return `${header([
    "Vendored by shadcnui-hono-jsx. DO NOT EDIT; run `bun run upstream:sync` and `bun run generate`.",
    `upstream: ${source.package}@${source.version}/${source.file} (sha256:${source.sha256})`,
    ...vendoredNoticeLines(),
  ])}\n\n${text}`
}
