import { existsSync, readdirSync } from "node:fs"
import path from "node:path"
import {
  type Catalog,
  findItem,
  readClientScript,
  readGenerated,
  readTemplate,
} from "./catalog"
import { configFile, readConfig, requireConfig } from "./config"
import { UsageError } from "./errors"
import { type PlannedFile, type WriteSummary, writeFiles } from "./files"
import { type FinalizeOptions, finalize } from "./finalize"
import {
  type Installer,
  missingDependencies,
  readPackageJson,
} from "./package-manager"
import {
  COMPONENTS_DIR,
  CONFIG_FILE,
  LICENSE_NOTICE_FILE,
  SCRIPTS_DIR,
  STYLES_DIR,
} from "./paths"
import {
  DEFAULT_PRESET,
  mergePreset,
  type Preset,
  type PresetPart,
  presetUrl,
  resolvePreset,
} from "./preset"
import { type FetchJson, fetchPresetTheme, type PresetFlags } from "./shadcn"
import { applyFonts, buildThemeCss } from "./theme"
import type { Variant } from "./variants"

export interface Context {
  /** Root of the user's project. */
  cwd: string
  catalog: Catalog
  fetch: FetchJson
  install: Installer
  log: (line: string) => void
}

/** A preset checked against what this version can install. */
interface Setup {
  preset: Preset
  flags: PresetFlags
  /** Template style, e.g. `base-nova`. */
  style: string
  variant: Variant
  finalize: FinalizeOptions
}

function setupFor(catalog: Catalog, preset: Preset, flags: PresetFlags): Setup {
  const style = `base-${preset.config.style}`
  const finalize: FinalizeOptions = { iconLibrary: preset.config.iconLibrary }
  const variant: Variant = {
    rtl: flags.rtl,
    menuColor: preset.config.menuColor,
  }
  if (!catalog.styles.includes(style)) {
    throw new UsageError(
      `shadcnui-hono-jsx does not support style "${preset.config.style}" yet (preset ${preset.code}, ${presetUrl(preset.code)}).`
    )
  }
  return { preset, flags, style, variant, finalize }
}

/** The license notice, which includes the license of the preset's icons. */
const noticeFile = (setup: Setup): PlannedFile => ({
  path: LICENSE_NOTICE_FILE,
  text: readGenerated(`notices/${setup.finalize.iconLibrary}.txt`),
})

/** `theme.css` for the preset (fetched from ui.shadcn.com) and the vendored `tailwind.css`. */
async function planTheme(
  ctx: Context,
  setup: Setup
): Promise<{ files: PlannedFile[]; dependencies: string[] }> {
  const { preset } = setup
  const fetched = await fetchPresetTheme(preset, setup.flags, ctx.fetch)
  const { theme, dependencies: fontPackages } = applyFonts(
    fetched.theme,
    fetched.fonts
  )
  const dependencies = [...ctx.catalog.themeDependencies, ...fontPackages]
  const known = new Set([...dependencies, "shadcn/tailwind.css"])
  const unknown = Object.keys(theme.css ?? {})
    .filter((key) => key.startsWith("@import"))
    .map((key) => key.match(/^@import "([^"]+)"$/)?.[1] ?? key)
    .filter((specifier) => !known.has(specifier))
  if (unknown.length > 0) {
    throw new UsageError(
      `The theme from ${fetched.url} imports ${unknown.join(", ")}, which this version of shadcnui-hono-jsx does not know. Update shadcnui-hono-jsx.`
    )
  }
  const css = buildThemeCss(theme, [
    `Generated by shadcnui-hono-jsx for the shadcn/ui preset ${preset.code} (${presetUrl(preset.code)}); \`shadcnui-hono-jsx apply\` rewrites this file.`,
    `upstream: shadcn/ui ${theme.name} theme (${fetched.url})`,
    ...ctx.catalog.noticeLines,
  ])
  return {
    files: [
      { path: `${STYLES_DIR}/theme.css`, text: css },
      {
        path: `${STYLES_DIR}/tailwind.css`,
        text: readGenerated("tailwind.css"),
      },
    ],
    dependencies,
  }
}

function componentFile(setup: Setup, name: string): PlannedFile {
  return {
    path: `${COMPONENTS_DIR}/${name}.tsx`,
    text: finalize(readTemplate(setup.style, name, setup.variant), {
      ...setup.finalize,
      preset: setup.preset.code,
    }),
  }
}

/** Files and packages of the named items, with the sibling components they import. */
function planItems(
  ctx: Context,
  setup: Setup,
  names: readonly string[]
): { files: PlannedFile[]; dependencies: string[]; scripts: string[] } {
  const items = names.map((name) => findItem(ctx.catalog, name))
  const components = [...new Set(items.flatMap((item) => item.components))]
  const scripts = [...new Set(items.flatMap((item) => item.scripts))].sort()
  return {
    files: [
      ...components.map((name) => componentFile(setup, name)),
      ...scripts.map((name) => ({
        path: `${SCRIPTS_DIR}/${name}.js`,
        text: readClientScript(name),
      })),
    ],
    dependencies: items.flatMap((item) => item.dependencies),
    scripts,
  }
}

/** Components of this project installed in `components/ui/`. */
function installedComponents(ctx: Context): string[] {
  const dir = path.join(ctx.cwd, COMPONENTS_DIR)
  if (!existsSync(dir)) return []
  const known = new Set(ctx.catalog.items.map((item) => item.name))
  return readdirSync(dir)
    .filter((file) => file.endsWith(".tsx"))
    .map((file) => file.slice(0, -".tsx".length))
    .filter((name) => known.has(name))
    .sort()
}

function installMissing(ctx: Context, packages: readonly string[]): void {
  const missing = missingDependencies(ctx.cwd, packages)
  if (missing.length > 0) ctx.install(ctx.cwd, missing)
}

function report(ctx: Context, summary: WriteSummary): void {
  for (const file of summary.created) ctx.log(`created ${file}`)
  for (const file of summary.updated) ctx.log(`updated ${file}`)
  if (summary.unchanged.length > 0) {
    ctx.log(`${summary.unchanged.length} file(s) already up to date`)
  }
}

/** Remix Icon's license restricts use, so `init` and `apply` point it out. */
function reportIconLicense(ctx: Context, setup: Setup): void {
  if (setup.finalize.iconLibrary !== "remixicon") return
  ctx.log(
    `Remix Icon is licensed under the Remix Icon License v1.0, which is not an open source license; read the Icons section of ${LICENSE_NOTICE_FILE} before you ship.`
  )
}

function reportScripts(ctx: Context, scripts: readonly string[]): void {
  const pages = scripts.filter((name) => name !== "core")
  if (pages.length === 0) return
  ctx.log(
    `Serve ${SCRIPTS_DIR}/ as static files at /shadcn/ and load ${pages.map((name) => `<script type="module" src="/shadcn/${name}.js">`).join(" and ")} on pages that use these components.`
  )
}

export interface InitOptions {
  preset?: string
  rtl: boolean
  pointer: boolean
  /** Replace an existing config and files with other content. */
  force: boolean
  components: string[]
}

/** Writes the config, theme and license notice, and optionally components. */
export async function init(ctx: Context, options: InitOptions): Promise<void> {
  readPackageJson(ctx.cwd)
  if (readConfig(ctx.cwd) && !options.force) {
    throw new UsageError(
      `${CONFIG_FILE} already exists. Use \`shadcnui-hono-jsx apply --preset <code>\` to change the preset, or \`init --force\` to start over.`
    )
  }
  const flags = { rtl: options.rtl, pointer: options.pointer }
  const setup = setupFor(
    ctx.catalog,
    resolvePreset(options.preset ?? DEFAULT_PRESET),
    flags
  )
  const theme = await planTheme(ctx, setup)
  const items = planItems(ctx, setup, options.components)
  const summary = writeFiles(
    ctx.cwd,
    [
      configFile({ preset: setup.preset.code, ...flags }),
      ...theme.files,
      noticeFile(setup),
      ...items.files,
    ],
    { overwrite: options.force, hint: "Pass --force to replace them." }
  )
  report(ctx, summary)
  installMissing(ctx, [...theme.dependencies, ...items.dependencies])
  reportIconLicense(ctx, setup)
  ctx.log(
    `Import the theme after Tailwind CSS in your stylesheet (@import "tailwindcss"; @import "<path>/${STYLES_DIR}/theme.css";), and let Tailwind scan ${COMPONENTS_DIR}/ (@source "<path>/${COMPONENTS_DIR}" when it is outside your source root).`
  )
  reportScripts(ctx, items.scripts)
}

export interface AddOptions {
  components: string[]
  /** Replace existing files with other content. */
  overwrite: boolean
}

/** Installs components for the project's preset. */
export async function add(ctx: Context, options: AddOptions): Promise<void> {
  if (options.components.length === 0) {
    throw new UsageError(
      `Name the components to add, e.g. \`shadcnui-hono-jsx add button\`. Available: ${ctx.catalog.items.map((item) => item.name).join(", ")}`
    )
  }
  readPackageJson(ctx.cwd)
  const config = requireConfig(ctx.cwd)
  const setup = setupFor(ctx.catalog, resolvePreset(config.preset), {
    rtl: config.rtl,
    pointer: config.pointer,
  })
  const items = planItems(ctx, setup, options.components)
  const summary = writeFiles(ctx.cwd, [...items.files, noticeFile(setup)], {
    overwrite: options.overwrite,
    hint: "Pass --overwrite to replace them.",
  })
  report(ctx, summary)
  installMissing(ctx, items.dependencies)
  reportScripts(ctx, items.scripts)
}

export interface ApplyOptions {
  preset?: string
  /** Take only these parts from the new preset and leave components alone. */
  only: PresetPart[]
  rtl?: boolean
  pointer?: boolean
}

/** Changes the preset and rewrites the theme and every installed component. */
export async function apply(
  ctx: Context,
  options: ApplyOptions
): Promise<void> {
  readPackageJson(ctx.cwd)
  const config = requireConfig(ctx.cwd)
  if (options.only.length > 0) {
    if (!options.preset) {
      throw new UsageError("--only needs --preset")
    }
    if (options.rtl !== undefined && options.rtl !== config.rtl) {
      throw new UsageError(
        "--rtl changes components, so it cannot be combined with --only"
      )
    }
  }
  const current = resolvePreset(config.preset)
  const requested = options.preset ? resolvePreset(options.preset) : current
  const preset =
    options.only.length > 0
      ? mergePreset(current, requested, options.only)
      : requested
  const flags = {
    rtl: options.rtl ?? config.rtl,
    pointer: options.pointer ?? config.pointer,
  }
  const setup = setupFor(ctx.catalog, preset, flags)
  const theme = await planTheme(ctx, setup)
  const installed = options.only.length > 0 ? [] : installedComponents(ctx)
  const summary = writeFiles(
    ctx.cwd,
    [
      configFile({ preset: preset.code, ...flags }),
      ...theme.files,
      noticeFile(setup),
      ...installed.map((name) => componentFile(setup, name)),
    ],
    { overwrite: true, hint: "" }
  )
  report(ctx, summary)
  installMissing(ctx, [
    ...theme.dependencies,
    ...installed.flatMap((name) => findItem(ctx.catalog, name).dependencies),
  ])
  reportIconLicense(ctx, setup)
}
