import { readGenerated } from "./catalog"
import {
  ICON_HELPER_MARKER,
  ICON_MARKER,
  type IconLibrary,
  type IconNames,
  type IconSet,
} from "./icons"

/**
 * Preset options that change component source at install time. Menu color
 * and RTL select a template variant instead (see `readTemplate`).
 */
export interface FinalizeOptions {
  iconLibrary: IconLibrary
}

const TEMPLATE_HEADER = /^\/\/ Generated by shadcnui-hono-jsx[^\n]*\n/
const ICONS_HEADER = /^\/\/ Icons: lucide@[^\n]*$/m
const escapeRegExp = (text: string) =>
  text.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&")
/** A marked icon: the marker, the doc comment and the function up to its closing line. */
const ICON_BLOCK = new RegExp(
  `^${escapeRegExp(ICON_MARKER)}(.*)\\n/\\*\\*[^\\n]*\\*/\\nfunction (\\w+)\\([\\s\\S]*?\\n\\}\\n`,
  "gm"
)
const ICON_HELPER_BLOCK = new RegExp(
  `^${escapeRegExp(ICON_HELPER_MARKER)}\\n/\\*\\*[^\\n]*\\*/\\nfunction hasA11yProp\\([\\s\\S]*?\\n\\}\\n\\n?`,
  "m"
)
const MARKER_LINES = new RegExp(
  `^(${escapeRegExp(ICON_MARKER)}.*|${escapeRegExp(ICON_HELPER_MARKER)})\\n`,
  "gm"
)

const iconSets = new Map<IconLibrary, IconSet>()

function readIconSet(library: IconLibrary): IconSet {
  let set = iconSets.get(library)
  if (!set) {
    set = JSON.parse(readGenerated(`icons/${library}.json`)) as IconSet
    iconSets.set(library, set)
  }
  return set
}

/**
 * Replaces the inlined Lucide icons of a template with the library's
 * (docs/adr/0031), keeping the local component names, and names them in the
 * header.
 */
function swapIcons(template: string, library: IconLibrary): string {
  if (library === "lucide") return template.replace(MARKER_LINES, "")
  const set = readIconSet(library)
  const names = new Set<string>()
  const swapped = template
    .replace(ICON_BLOCK, (_, json: string, component: string) => {
      const name = (JSON.parse(json) as IconNames)[library]
      const icon = set.icons[name]
      if (!icon) throw new Error(`No ${library} icon ${name} for ${component}`)
      names.add(icon.name)
      return `${icon.source.trimEnd().replaceAll("__COMPONENT__", component)}\n`
    })
    .replace(ICON_HELPER_BLOCK, "")
  if (names.size === 0) return template
  if (swapped.includes(ICON_MARKER) || swapped.includes(ICON_HELPER_MARKER)) {
    throw new Error("template has icon markers finalize cannot swap")
  }
  if (!ICONS_HEADER.test(swapped)) {
    throw new Error("template with icons has no Icons header line")
  }
  return swapped.replace(
    ICONS_HEADER,
    () =>
      `// ${set.headerLine.replace("{names}", [...names].sort().join(", "))}`
  )
}

/**
 * Turns a template (of the variant for the preset's menu color and
 * direction) into the installed component. Templates are the final Hono JSX
 * except for the icon library; the header's first line addresses repository
 * maintainers and is replaced.
 */
export function finalize(
  template: string,
  options: FinalizeOptions & { preset: string }
): string {
  if (!TEMPLATE_HEADER.test(template)) {
    throw new Error("template does not start with the generated header")
  }
  return swapIcons(template, options.iconLibrary).replace(
    TEMPLATE_HEADER,
    `// Installed by shadcnui-hono-jsx for the shadcn/ui preset ${options.preset}; \`shadcnui-hono-jsx apply\` rewrites this file.\n`
  )
}
