import type { PresetConfig } from "./preset"

/** Preset options that change component source (docs/adr/0030). */
export interface FinalizeOptions {
  iconLibrary: PresetConfig["iconLibrary"]
  menuColor: PresetConfig["menuColor"]
  rtl: boolean
}

/** Option values finalize can produce so far; `init` and `apply` reject others. */
export const SUPPORTED_OPTIONS: {
  readonly [K in keyof FinalizeOptions]: readonly FinalizeOptions[K][]
} = {
  iconLibrary: ["lucide"],
  menuColor: ["default"],
  rtl: [false],
}

/** Options of `FinalizeOptions` that finalize cannot produce yet. */
export function unsupportedOptions(options: FinalizeOptions): string[] {
  return (Object.keys(SUPPORTED_OPTIONS) as (keyof FinalizeOptions)[])
    .filter(
      (key) =>
        !(SUPPORTED_OPTIONS[key] as readonly unknown[]).includes(options[key])
    )
    .map((key) => `${key} "${String(options[key])}"`)
}

const TEMPLATE_HEADER = /^\/\/ Generated by shadcnui-hono-jsx[^\n]*\n/

/**
 * Turns a template into the installed component. Templates are the final Hono
 * JSX except for the install-time variation points of docs/adr/0030; the
 * header's first line addresses repository maintainers and is replaced.
 */
export function finalize(
  template: string,
  options: FinalizeOptions & { preset: string }
): string {
  const problems = unsupportedOptions(options)
  if (problems.length > 0) {
    throw new Error(`finalize does not support ${problems.join(", ")} yet`)
  }
  if (!TEMPLATE_HEADER.test(template)) {
    throw new Error("template does not start with the generated header")
  }
  return template.replace(
    TEMPLATE_HEADER,
    `// Installed by shadcnui-hono-jsx for the shadcn/ui preset ${options.preset}; \`shadcnui-hono-jsx apply\` rewrites this file.\n`
  )
}
