import type { Preset } from "./preset"
import {
  type FetchJson,
  fetchPresetTheme,
  type PresetFlags,
  presetUrl,
} from "./shadcn"
import { applyFonts, buildThemeCss, type ThemeItem } from "./theme"

export interface PresetTheme {
  /** The `/init` URL the theme came from. */
  url: string
  /** The theme with the preset's fonts applied. */
  theme: ThemeItem
  /** `styles/shadcn/theme.css` as `init` writes it. */
  css: string
  /** `@fontsource-variable/*` packages of the preset's fonts. */
  fontPackages: string[]
}

/**
 * Fetches a preset's theme and builds `theme.css`. It uses no file system, so
 * the documentation site's Worker shows exactly what `init` writes.
 */
export async function presetTheme(
  preset: Preset,
  flags: PresetFlags,
  fetch: FetchJson,
  noticeLines: readonly string[]
): Promise<PresetTheme> {
  const fetched = await fetchPresetTheme(preset, flags, fetch)
  const { theme, dependencies } = applyFonts(fetched.theme, fetched.fonts)
  const css = buildThemeCss(theme, [
    `Generated by shadcnui-hono-jsx for the shadcn/ui preset ${preset.code} (${presetUrl(preset.code)}); \`shadcnui-hono-jsx apply\` rewrites this file.`,
    `upstream: shadcn/ui ${theme.name} theme (${fetched.url})`,
    ...noticeLines,
  ])
  return { url: fetched.url, theme, css, fontPackages: dependencies }
}
